### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by reeses-pieces**
@Bontgoy

Can you review our approach here? I'm especially curious about decrypt. I also hopefully optimized the code as illustrated in the commit history. Let me know your thoughts. Thanks!

### CODE REVIEW

**Comment by Bontgoy** [comment]
@reeses-pieces I started refactoring this and then I realized its pretty optimized.  Nice work!

One piece of advice would be to not name variables key words like `index`

instead name it after what it is tracking or doing.  Perhaps `index_counter`.  Try and be explicit with your names while avoiding words that may already be built in methods.

**Comment by reeses-pieces** [comment]
@Bontgoy
Thanks for checking. If it's not advised to use index as a variable, why is it in the example that was provided to us? On Release 2, the documentation provided an example for looping through letters of a string: https://repl.it/Bjc6/1

**Comment by Bontgoy** [comment]
That is a fair question and because of it you started a lively discussion about conventions between my boss and I.  I feel that we should be more explicit with our variable naming and he respectfully argued that my convention is too preemptive for an implicit language like Ruby.  So, thanks for allowing me to get a bit more insight on the code as well and feel free to use index as a variable name.

**Comment by reeses-pieces** [comment]
No worries. I know every programmer has different philosophies. It reminds me of a scene in the HBO series Silicon Valley where there is a lively debate on tabs vs. spaces!

**Comment by Bontgoy** [comment]
@reeses-pieces haha that is such an awesome episode.  BTW my boss is a space guy so I am by extension

**Pull request merged**
